# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('urlpath', models.CharField(max_length=70)),
                ('click', models.IntegerField(default=1)),
                ('update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=70)),
                ('grap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grap.grap')),
            ],
        ),
    ]
