# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JokeJi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokeji',
            old_name='tittle',
            new_name='title',
        ),
    ]
